Require traces

Set Shell "bash"
Set Theme "Catppuccin Macchiato"
Set FontSize 17
Set Width 1400
Set Height 850
Set Padding 22
Set Framerate 20
Set TypingSpeed 45ms

Sleep 2s
Type "traces -all -provider , -file orc-ci.jsonl"
Enter
Wait+Screen /GitHub Actions/
Type "ggzMl"
Wait+Screen /Orc CI/
Sleep 7s
Type "j"
Sleep 4s
Type "l"
Sleep 7s
Tab
Sleep 8s
Type "hj"
Sleep 4s
Type "l"
Sleep 8s
Tab
Sleep 5s
Type "q"
Sleep 3s
