name: Generated documentation
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop -c uv run --offline --no-managed-python --no-python-downloads --python python3 --script hack/extra-docs.py --check
      - run: nix develop -c uv run --offline --no-managed-python --no-python-downloads --python python3 --script hack/extra-demos.py --check
      - run: nix shell --inputs-from . nixpkgs#uv nixpkgs#python3 -c uv run --offline --no-python-downloads --script hack/test_update_flakes.py
      - run: nix develop -c uv run --offline --no-managed-python --no-python-downloads --python python3 --script hack/release-extras.py --check
